const githubResult = """
  {
  "total_count": 379,
  "incomplete_results": false,
  "items": [
    {
      "login": "thiagosf",
      "id": 319234,
      "node_id": "MDQ6VXNlcjMxOTIzNA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/319234?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thiagosf",
      "html_url": "https://github.com/thiagosf",
      "followers_url": "https://api.github.com/users/thiagosf/followers",
      "following_url": "https://api.github.com/users/thiagosf/following{/other_user}",
      "gists_url": "https://api.github.com/users/thiagosf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thiagosf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thiagosf/subscriptions",
      "organizations_url": "https://api.github.com/users/thiagosf/orgs",
      "repos_url": "https://api.github.com/users/thiagosf/repos",
      "events_url": "https://api.github.com/users/thiagosf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thiagosf/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "ThiagoPederzolli",
      "id": 64425083,
      "node_id": "MDQ6VXNlcjY0NDI1MDgz",
      "avatar_url": "https://avatars.githubusercontent.com/u/64425083?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ThiagoPederzolli",
      "html_url": "https://github.com/ThiagoPederzolli",
      "followers_url": "https://api.github.com/users/ThiagoPederzolli/followers",
      "following_url": "https://api.github.com/users/ThiagoPederzolli/following{/other_user}",
      "gists_url": "https://api.github.com/users/ThiagoPederzolli/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ThiagoPederzolli/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ThiagoPederzolli/subscriptions",
      "organizations_url": "https://api.github.com/users/ThiagoPederzolli/orgs",
      "repos_url": "https://api.github.com/users/ThiagoPederzolli/repos",
      "events_url": "https://api.github.com/users/ThiagoPederzolli/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ThiagoPederzolli/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "programadriano",
      "id": 355275,
      "node_id": "MDQ6VXNlcjM1NTI3NQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/355275?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/programadriano",
      "html_url": "https://github.com/programadriano",
      "followers_url": "https://api.github.com/users/programadriano/followers",
      "following_url": "https://api.github.com/users/programadriano/following{/other_user}",
      "gists_url": "https://api.github.com/users/programadriano/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/programadriano/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/programadriano/subscriptions",
      "organizations_url": "https://api.github.com/users/programadriano/orgs",
      "repos_url": "https://api.github.com/users/programadriano/repos",
      "events_url": "https://api.github.com/users/programadriano/events{/privacy}",
      "received_events_url": "https://api.github.com/users/programadriano/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "silva-thiago",
      "id": 20340261,
      "node_id": "MDQ6VXNlcjIwMzQwMjYx",
      "avatar_url": "https://avatars.githubusercontent.com/u/20340261?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/silva-thiago",
      "html_url": "https://github.com/silva-thiago",
      "followers_url": "https://api.github.com/users/silva-thiago/followers",
      "following_url": "https://api.github.com/users/silva-thiago/following{/other_user}",
      "gists_url": "https://api.github.com/users/silva-thiago/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/silva-thiago/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/silva-thiago/subscriptions",
      "organizations_url": "https://api.github.com/users/silva-thiago/orgs",
      "repos_url": "https://api.github.com/users/silva-thiago/repos",
      "events_url": "https://api.github.com/users/silva-thiago/events{/privacy}",
      "received_events_url": "https://api.github.com/users/silva-thiago/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "pgThiago",
      "id": 48173784,
      "node_id": "MDQ6VXNlcjQ4MTczNzg0",
      "avatar_url": "https://avatars.githubusercontent.com/u/48173784?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/pgThiago",
      "html_url": "https://github.com/pgThiago",
      "followers_url": "https://api.github.com/users/pgThiago/followers",
      "following_url": "https://api.github.com/users/pgThiago/following{/other_user}",
      "gists_url": "https://api.github.com/users/pgThiago/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/pgThiago/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/pgThiago/subscriptions",
      "organizations_url": "https://api.github.com/users/pgThiago/orgs",
      "repos_url": "https://api.github.com/users/pgThiago/repos",
      "events_url": "https://api.github.com/users/pgThiago/events{/privacy}",
      "received_events_url": "https://api.github.com/users/pgThiago/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thiagoandrecardoso",
      "id": 33556919,
      "node_id": "MDQ6VXNlcjMzNTU2OTE5",
      "avatar_url": "https://avatars.githubusercontent.com/u/33556919?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thiagoandrecardoso",
      "html_url": "https://github.com/thiagoandrecardoso",
      "followers_url": "https://api.github.com/users/thiagoandrecardoso/followers",
      "following_url": "https://api.github.com/users/thiagoandrecardoso/following{/other_user}",
      "gists_url": "https://api.github.com/users/thiagoandrecardoso/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thiagoandrecardoso/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thiagoandrecardoso/subscriptions",
      "organizations_url": "https://api.github.com/users/thiagoandrecardoso/orgs",
      "repos_url": "https://api.github.com/users/thiagoandrecardoso/repos",
      "events_url": "https://api.github.com/users/thiagoandrecardoso/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thiagoandrecardoso/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thiagoa",
      "id": 746384,
      "node_id": "MDQ6VXNlcjc0NjM4NA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/746384?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thiagoa",
      "html_url": "https://github.com/thiagoa",
      "followers_url": "https://api.github.com/users/thiagoa/followers",
      "following_url": "https://api.github.com/users/thiagoa/following{/other_user}",
      "gists_url": "https://api.github.com/users/thiagoa/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thiagoa/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thiagoa/subscriptions",
      "organizations_url": "https://api.github.com/users/thiagoa/orgs",
      "repos_url": "https://api.github.com/users/thiagoa/repos",
      "events_url": "https://api.github.com/users/thiagoa/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thiagoa/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thiagoasb",
      "id": 38672183,
      "node_id": "MDQ6VXNlcjM4NjcyMTgz",
      "avatar_url": "https://avatars.githubusercontent.com/u/38672183?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thiagoasb",
      "html_url": "https://github.com/thiagoasb",
      "followers_url": "https://api.github.com/users/thiagoasb/followers",
      "following_url": "https://api.github.com/users/thiagoasb/following{/other_user}",
      "gists_url": "https://api.github.com/users/thiagoasb/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thiagoasb/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thiagoasb/subscriptions",
      "organizations_url": "https://api.github.com/users/thiagoasb/orgs",
      "repos_url": "https://api.github.com/users/thiagoasb/repos",
      "events_url": "https://api.github.com/users/thiagoasb/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thiagoasb/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "th1ag0-Zz",
      "id": 61771003,
      "node_id": "MDQ6VXNlcjYxNzcxMDAz",
      "avatar_url": "https://avatars.githubusercontent.com/u/61771003?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/th1ag0-Zz",
      "html_url": "https://github.com/th1ag0-Zz",
      "followers_url": "https://api.github.com/users/th1ag0-Zz/followers",
      "following_url": "https://api.github.com/users/th1ag0-Zz/following{/other_user}",
      "gists_url": "https://api.github.com/users/th1ag0-Zz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/th1ag0-Zz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/th1ag0-Zz/subscriptions",
      "organizations_url": "https://api.github.com/users/th1ag0-Zz/orgs",
      "repos_url": "https://api.github.com/users/th1ag0-Zz/repos",
      "events_url": "https://api.github.com/users/th1ag0-Zz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/th1ag0-Zz/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thiagoolsilva",
      "id": 1016855,
      "node_id": "MDQ6VXNlcjEwMTY4NTU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1016855?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thiagoolsilva",
      "html_url": "https://github.com/thiagoolsilva",
      "followers_url": "https://api.github.com/users/thiagoolsilva/followers",
      "following_url": "https://api.github.com/users/thiagoolsilva/following{/other_user}",
      "gists_url": "https://api.github.com/users/thiagoolsilva/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thiagoolsilva/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thiagoolsilva/subscriptions",
      "organizations_url": "https://api.github.com/users/thiagoolsilva/orgs",
      "repos_url": "https://api.github.com/users/thiagoolsilva/repos",
      "events_url": "https://api.github.com/users/thiagoolsilva/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thiagoolsilva/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thiagosilva2",
      "id": 65048868,
      "node_id": "MDQ6VXNlcjY1MDQ4ODY4",
      "avatar_url": "https://avatars.githubusercontent.com/u/65048868?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thiagosilva2",
      "html_url": "https://github.com/thiagosilva2",
      "followers_url": "https://api.github.com/users/thiagosilva2/followers",
      "following_url": "https://api.github.com/users/thiagosilva2/following{/other_user}",
      "gists_url": "https://api.github.com/users/thiagosilva2/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thiagosilva2/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thiagosilva2/subscriptions",
      "organizations_url": "https://api.github.com/users/thiagosilva2/orgs",
      "repos_url": "https://api.github.com/users/thiagosilva2/repos",
      "events_url": "https://api.github.com/users/thiagosilva2/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thiagosilva2/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thiagodasilva",
      "id": 1494299,
      "node_id": "MDQ6VXNlcjE0OTQyOTk=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1494299?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thiagodasilva",
      "html_url": "https://github.com/thiagodasilva",
      "followers_url": "https://api.github.com/users/thiagodasilva/followers",
      "following_url": "https://api.github.com/users/thiagodasilva/following{/other_user}",
      "gists_url": "https://api.github.com/users/thiagodasilva/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thiagodasilva/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thiagodasilva/subscriptions",
      "organizations_url": "https://api.github.com/users/thiagodasilva/orgs",
      "repos_url": "https://api.github.com/users/thiagodasilva/repos",
      "events_url": "https://api.github.com/users/thiagodasilva/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thiagodasilva/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thiagodds",
      "id": 2293088,
      "node_id": "MDQ6VXNlcjIyOTMwODg=",
      "avatar_url": "https://avatars.githubusercontent.com/u/2293088?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thiagodds",
      "html_url": "https://github.com/thiagodds",
      "followers_url": "https://api.github.com/users/thiagodds/followers",
      "following_url": "https://api.github.com/users/thiagodds/following{/other_user}",
      "gists_url": "https://api.github.com/users/thiagodds/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thiagodds/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thiagodds/subscriptions",
      "organizations_url": "https://api.github.com/users/thiagodds/orgs",
      "repos_url": "https://api.github.com/users/thiagodds/repos",
      "events_url": "https://api.github.com/users/thiagodds/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thiagodds/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "s7Thiago",
      "id": 37230912,
      "node_id": "MDQ6VXNlcjM3MjMwOTEy",
      "avatar_url": "https://avatars.githubusercontent.com/u/37230912?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/s7Thiago",
      "html_url": "https://github.com/s7Thiago",
      "followers_url": "https://api.github.com/users/s7Thiago/followers",
      "following_url": "https://api.github.com/users/s7Thiago/following{/other_user}",
      "gists_url": "https://api.github.com/users/s7Thiago/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/s7Thiago/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/s7Thiago/subscriptions",
      "organizations_url": "https://api.github.com/users/s7Thiago/orgs",
      "repos_url": "https://api.github.com/users/s7Thiago/repos",
      "events_url": "https://api.github.com/users/s7Thiago/events{/privacy}",
      "received_events_url": "https://api.github.com/users/s7Thiago/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thiagosantos346",
      "id": 12611170,
      "node_id": "MDQ6VXNlcjEyNjExMTcw",
      "avatar_url": "https://avatars.githubusercontent.com/u/12611170?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thiagosantos346",
      "html_url": "https://github.com/thiagosantos346",
      "followers_url": "https://api.github.com/users/thiagosantos346/followers",
      "following_url": "https://api.github.com/users/thiagosantos346/following{/other_user}",
      "gists_url": "https://api.github.com/users/thiagosantos346/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thiagosantos346/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thiagosantos346/subscriptions",
      "organizations_url": "https://api.github.com/users/thiagosantos346/orgs",
      "repos_url": "https://api.github.com/users/thiagosantos346/repos",
      "events_url": "https://api.github.com/users/thiagosantos346/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thiagosantos346/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thiagosfsilva",
      "id": 3610888,
      "node_id": "MDQ6VXNlcjM2MTA4ODg=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3610888?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thiagosfsilva",
      "html_url": "https://github.com/thiagosfsilva",
      "followers_url": "https://api.github.com/users/thiagosfsilva/followers",
      "following_url": "https://api.github.com/users/thiagosfsilva/following{/other_user}",
      "gists_url": "https://api.github.com/users/thiagosfsilva/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thiagosfsilva/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thiagosfsilva/subscriptions",
      "organizations_url": "https://api.github.com/users/thiagosfsilva/orgs",
      "repos_url": "https://api.github.com/users/thiagosfsilva/repos",
      "events_url": "https://api.github.com/users/thiagosfsilva/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thiagosfsilva/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thiago-hs",
      "id": 29106664,
      "node_id": "MDQ6VXNlcjI5MTA2NjY0",
      "avatar_url": "https://avatars.githubusercontent.com/u/29106664?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thiago-hs",
      "html_url": "https://github.com/thiago-hs",
      "followers_url": "https://api.github.com/users/thiago-hs/followers",
      "following_url": "https://api.github.com/users/thiago-hs/following{/other_user}",
      "gists_url": "https://api.github.com/users/thiago-hs/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thiago-hs/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thiago-hs/subscriptions",
      "organizations_url": "https://api.github.com/users/thiago-hs/orgs",
      "repos_url": "https://api.github.com/users/thiago-hs/repos",
      "events_url": "https://api.github.com/users/thiago-hs/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thiago-hs/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "xThiagoSant",
      "id": 45977226,
      "node_id": "MDQ6VXNlcjQ1OTc3MjI2",
      "avatar_url": "https://avatars.githubusercontent.com/u/45977226?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/xThiagoSant",
      "html_url": "https://github.com/xThiagoSant",
      "followers_url": "https://api.github.com/users/xThiagoSant/followers",
      "following_url": "https://api.github.com/users/xThiagoSant/following{/other_user}",
      "gists_url": "https://api.github.com/users/xThiagoSant/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/xThiagoSant/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/xThiagoSant/subscriptions",
      "organizations_url": "https://api.github.com/users/xThiagoSant/orgs",
      "repos_url": "https://api.github.com/users/xThiagoSant/repos",
      "events_url": "https://api.github.com/users/xThiagoSant/events{/privacy}",
      "received_events_url": "https://api.github.com/users/xThiagoSant/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thiagosilva2004",
      "id": 61203051,
      "node_id": "MDQ6VXNlcjYxMjAzMDUx",
      "avatar_url": "https://avatars.githubusercontent.com/u/61203051?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thiagosilva2004",
      "html_url": "https://github.com/thiagosilva2004",
      "followers_url": "https://api.github.com/users/thiagosilva2004/followers",
      "following_url": "https://api.github.com/users/thiagosilva2004/following{/other_user}",
      "gists_url": "https://api.github.com/users/thiagosilva2004/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thiagosilva2004/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thiagosilva2004/subscriptions",
      "organizations_url": "https://api.github.com/users/thiagosilva2004/orgs",
      "repos_url": "https://api.github.com/users/thiagosilva2004/repos",
      "events_url": "https://api.github.com/users/thiagosilva2004/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thiagosilva2004/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thicsilva",
      "id": 3330664,
      "node_id": "MDQ6VXNlcjMzMzA2NjQ=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3330664?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thicsilva",
      "html_url": "https://github.com/thicsilva",
      "followers_url": "https://api.github.com/users/thicsilva/followers",
      "following_url": "https://api.github.com/users/thicsilva/following{/other_user}",
      "gists_url": "https://api.github.com/users/thicsilva/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thicsilva/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thicsilva/subscriptions",
      "organizations_url": "https://api.github.com/users/thicsilva/orgs",
      "repos_url": "https://api.github.com/users/thicsilva/repos",
      "events_url": "https://api.github.com/users/thicsilva/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thicsilva/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Thiago-AS",
      "id": 33294875,
      "node_id": "MDQ6VXNlcjMzMjk0ODc1",
      "avatar_url": "https://avatars.githubusercontent.com/u/33294875?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Thiago-AS",
      "html_url": "https://github.com/Thiago-AS",
      "followers_url": "https://api.github.com/users/Thiago-AS/followers",
      "following_url": "https://api.github.com/users/Thiago-AS/following{/other_user}",
      "gists_url": "https://api.github.com/users/Thiago-AS/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Thiago-AS/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Thiago-AS/subscriptions",
      "organizations_url": "https://api.github.com/users/Thiago-AS/orgs",
      "repos_url": "https://api.github.com/users/Thiago-AS/repos",
      "events_url": "https://api.github.com/users/Thiago-AS/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Thiago-AS/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thihenos",
      "id": 11467539,
      "node_id": "MDQ6VXNlcjExNDY3NTM5",
      "avatar_url": "https://avatars.githubusercontent.com/u/11467539?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thihenos",
      "html_url": "https://github.com/thihenos",
      "followers_url": "https://api.github.com/users/thihenos/followers",
      "following_url": "https://api.github.com/users/thihenos/following{/other_user}",
      "gists_url": "https://api.github.com/users/thihenos/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thihenos/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thihenos/subscriptions",
      "organizations_url": "https://api.github.com/users/thihenos/orgs",
      "repos_url": "https://api.github.com/users/thihenos/repos",
      "events_url": "https://api.github.com/users/thihenos/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thihenos/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thiagoadssilva",
      "id": 23080516,
      "node_id": "MDQ6VXNlcjIzMDgwNTE2",
      "avatar_url": "https://avatars.githubusercontent.com/u/23080516?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thiagoadssilva",
      "html_url": "https://github.com/thiagoadssilva",
      "followers_url": "https://api.github.com/users/thiagoadssilva/followers",
      "following_url": "https://api.github.com/users/thiagoadssilva/following{/other_user}",
      "gists_url": "https://api.github.com/users/thiagoadssilva/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thiagoadssilva/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thiagoadssilva/subscriptions",
      "organizations_url": "https://api.github.com/users/thiagoadssilva/orgs",
      "repos_url": "https://api.github.com/users/thiagoadssilva/repos",
      "events_url": "https://api.github.com/users/thiagoadssilva/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thiagoadssilva/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thiagoviks",
      "id": 62107168,
      "node_id": "MDQ6VXNlcjYyMTA3MTY4",
      "avatar_url": "https://avatars.githubusercontent.com/u/62107168?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thiagoviks",
      "html_url": "https://github.com/thiagoviks",
      "followers_url": "https://api.github.com/users/thiagoviks/followers",
      "following_url": "https://api.github.com/users/thiagoviks/following{/other_user}",
      "gists_url": "https://api.github.com/users/thiagoviks/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thiagoviks/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thiagoviks/subscriptions",
      "organizations_url": "https://api.github.com/users/thiagoviks/orgs",
      "repos_url": "https://api.github.com/users/thiagoviks/repos",
      "events_url": "https://api.github.com/users/thiagoviks/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thiagoviks/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thiagouft",
      "id": 22283017,
      "node_id": "MDQ6VXNlcjIyMjgzMDE3",
      "avatar_url": "https://avatars.githubusercontent.com/u/22283017?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thiagouft",
      "html_url": "https://github.com/thiagouft",
      "followers_url": "https://api.github.com/users/thiagouft/followers",
      "following_url": "https://api.github.com/users/thiagouft/following{/other_user}",
      "gists_url": "https://api.github.com/users/thiagouft/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thiagouft/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thiagouft/subscriptions",
      "organizations_url": "https://api.github.com/users/thiagouft/orgs",
      "repos_url": "https://api.github.com/users/thiagouft/repos",
      "events_url": "https://api.github.com/users/thiagouft/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thiagouft/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Thiagoow",
      "id": 71602458,
      "node_id": "MDQ6VXNlcjcxNjAyNDU4",
      "avatar_url": "https://avatars.githubusercontent.com/u/71602458?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Thiagoow",
      "html_url": "https://github.com/Thiagoow",
      "followers_url": "https://api.github.com/users/Thiagoow/followers",
      "following_url": "https://api.github.com/users/Thiagoow/following{/other_user}",
      "gists_url": "https://api.github.com/users/Thiagoow/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Thiagoow/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Thiagoow/subscriptions",
      "organizations_url": "https://api.github.com/users/Thiagoow/orgs",
      "repos_url": "https://api.github.com/users/Thiagoow/repos",
      "events_url": "https://api.github.com/users/Thiagoow/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Thiagoow/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thiagosftk",
      "id": 33358564,
      "node_id": "MDQ6VXNlcjMzMzU4NTY0",
      "avatar_url": "https://avatars.githubusercontent.com/u/33358564?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thiagosftk",
      "html_url": "https://github.com/thiagosftk",
      "followers_url": "https://api.github.com/users/thiagosftk/followers",
      "following_url": "https://api.github.com/users/thiagosftk/following{/other_user}",
      "gists_url": "https://api.github.com/users/thiagosftk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thiagosftk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thiagosftk/subscriptions",
      "organizations_url": "https://api.github.com/users/thiagosftk/orgs",
      "repos_url": "https://api.github.com/users/thiagosftk/repos",
      "events_url": "https://api.github.com/users/thiagosftk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thiagosftk/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Thiago-Source",
      "id": 85903292,
      "node_id": "MDQ6VXNlcjg1OTAzMjky",
      "avatar_url": "https://avatars.githubusercontent.com/u/85903292?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Thiago-Source",
      "html_url": "https://github.com/Thiago-Source",
      "followers_url": "https://api.github.com/users/Thiago-Source/followers",
      "following_url": "https://api.github.com/users/Thiago-Source/following{/other_user}",
      "gists_url": "https://api.github.com/users/Thiago-Source/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Thiago-Source/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Thiago-Source/subscriptions",
      "organizations_url": "https://api.github.com/users/Thiago-Source/orgs",
      "repos_url": "https://api.github.com/users/Thiago-Source/repos",
      "events_url": "https://api.github.com/users/Thiago-Source/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Thiago-Source/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thiagolu",
      "id": 12925722,
      "node_id": "MDQ6VXNlcjEyOTI1NzIy",
      "avatar_url": "https://avatars.githubusercontent.com/u/12925722?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thiagolu",
      "html_url": "https://github.com/thiagolu",
      "followers_url": "https://api.github.com/users/thiagolu/followers",
      "following_url": "https://api.github.com/users/thiagolu/following{/other_user}",
      "gists_url": "https://api.github.com/users/thiagolu/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thiagolu/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thiagolu/subscriptions",
      "organizations_url": "https://api.github.com/users/thiagolu/orgs",
      "repos_url": "https://api.github.com/users/thiagolu/repos",
      "events_url": "https://api.github.com/users/thiagolu/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thiagolu/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "thiagodasilvag1989",
      "id": 49212173,
      "node_id": "MDQ6VXNlcjQ5MjEyMTcz",
      "avatar_url": "https://avatars.githubusercontent.com/u/49212173?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thiagodasilvag1989",
      "html_url": "https://github.com/thiagodasilvag1989",
      "followers_url": "https://api.github.com/users/thiagodasilvag1989/followers",
      "following_url": "https://api.github.com/users/thiagodasilvag1989/following{/other_user}",
      "gists_url": "https://api.github.com/users/thiagodasilvag1989/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thiagodasilvag1989/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thiagodasilvag1989/subscriptions",
      "organizations_url": "https://api.github.com/users/thiagodasilvag1989/orgs",
      "repos_url": "https://api.github.com/users/thiagodasilvag1989/repos",
      "events_url": "https://api.github.com/users/thiagodasilvag1989/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thiagodasilvag1989/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    }
  ]
}
""";
